SET_SCENE_TYPE INVESTIGATION 

CHARACTER_INITIALIZE Gumshoe characters/gumshoe 
CHARACTER_LOCATION Gumshoe LOBBY

TYPEWRITER
    "August 3rd, 10:05AM#District Court#Defendant Lobby No. 1"

PLAY_MUSIC PRELUDE

JUMPCUT LOBBY

DEFINE ExamineLobby
    SPEAK Gumshoe
        "howdy"

    CHOICE 
        "peepee" ExamineLobby
        "poopoo " 0
        "heehee" 0
        "doodoo" 0

END_DEFINE

JUMP ExamineLobby






    
