CHARACTER_INITIALIZE Phoenix characters/phoenix 
CHARACTER_INITIALIZE Edgeworth characters/edgeworth 

CHARACTER_LOCATION Phoenix COURT_DEFENSE
CHARACTER_LOCATION Edgeworth COURT_PROSECUTION

// Comments also work!

JUMPCUT COURT_DEFENSE
SPEAK Phoenix 
    "hello again edgeworth"

JUMPCUT COURT_PROSECUTION
SPEAK Edgeworth 
    "hello, peenix"

JUMPCUT COURT_DEFENSE
SPEAK Phoenix 
    "edgeworth, why am i always followed by ghosts?"

JUMPCUT COURT_PROSECUTION
SPEAK Edgeworth 
    "..."

JUMPCUT COURT_DEFENSE
POSE Phoenix POINT
OBJECTION Phoenix
SPEAK Phoenix 
    "shut your mouth edgeworth!"


