////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// INITIALIZE SCENE
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

SET_SCENE_TYPE INVESTIGATION

CHARACTER_INITIALIZE Arin arin MALE
CHARACTER_INITIALIZE Dan dan FEMALE
CHARACTER_INITIALIZE Jory jory MALE

EVIDENCE_INITIALIZE Badge "Attorney's Badge" "My prized possession." evidence/badge.png
COURT_RECORD_ADD EVIDENCE Badge

PLAY_MUSIC PRELUDE
JUMPCUT LOBBY

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// START SCRIPT
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

CHARACTER_LOCATION Jory LOBBY
POSE Jory Sweaty
SPEAK Arin
    "That sucks dude."

CHARACTER_LOCATION Dan LOBBY
POSE Dan Normal
SPEAK Dan
    "Arin, don't you get it?"
SPEAK Arin
    "Get what?"
SPEAK Dan
    "He wants US to defend him in this trial!#Right, Jory?"

POSE Jory ThumbsUp
CHARACTER_LOCATION Jory LOBBY

SCREEN_SHAKE
SFX Damage1
SPEAK Arin
    "Whaaaat?!"
SCREEN_SHAKE
SFX Damage1

WAIT 1
SPEAK Jory
    "Well, I guess so."
SPEAK Jory
    "I didn't really know what to do, and you guys know I'd never do anything like that."
SPEAK Arin
    "Well, I'm not really sure about all this..."

CHARACTER_LOCATION Dan LOBBY
POSE Dan Ohmy
SPEAK Dan
    "ARIN!"

POSE Dan Normal
SPEAK Dan
    "Cmon bro, be a bro and bro this one out for our bro... Brory."

END_SCENE