name: Generate executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build-upload:
    name: Generate self-contained archives
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vimaster/love-build@v2
      id: love-build
      with:
        app_name: 'Game Grumps - Joint Justice'
        love_version: '11.3'
    - uses: actions/upload-artifact@v1
      with:
        name: macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: win64-build
        path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: love-build
        path: ${{ steps.love-build.outputs.love-filename }}
